USE [master]
GO

/****** Object:  Database [CGDB]    Script Date: 2/3/2024 10:40:21 AM ******/
CREATE DATABASE [CGDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'test_CGDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\test_CGDB.mdf' , SIZE = 4096KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'test_CGDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\test_CGDB_log.ldf' , SIZE = 1536KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [CGDB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CGDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [CGDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [CGDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [CGDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [CGDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [CGDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [CGDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [CGDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [CGDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [CGDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [CGDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [CGDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [CGDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [CGDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [CGDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [CGDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [CGDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [CGDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [CGDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [CGDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [CGDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [CGDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [CGDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [CGDB] SET RECOVERY FULL 
GO

ALTER DATABASE [CGDB] SET  MULTI_USER 
GO

ALTER DATABASE [CGDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [CGDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [CGDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [CGDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [CGDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [CGDB] SET  READ_WRITE 
GO

